### ISSUE TITLE
Memory leak: old results are not deleted from the cache

### ISSUE THREAD

**Issue by juancampa** [sindresorhus/mem#14]
Looking at the code it seems like old results are never removed from the cache, even when they reach their maxAge and become forever unused. I might be misreading it though.

**Comment by sindresorhus** [comment]
Even if you can't submit a fix, submitting a pull request with a [failing test](https://github.com/avajs/ava#failing-tests) would be very helpful.

**Comment by greghawk** [comment]
@sindresorhus @keithamus  Is there a fix for this? it is blowing out my servers memory at volume

**Comment by keithamus** [comment]
@greghawk for now you have to pass in your own `Map` as the `{cache}` option - and then using a timer of your own, empty the `Map`.

**Comment by SamVerschueren** [comment]
I'm implementing it as we speak for [expiry-map](https://github.com/SamVerschueren/expiry-map) as it was reported as an [issue](https://github.com/SamVerschueren/expiry-map/issues/2) over there as well.

Because I also need it for [expiry-set](https://github.com/SamVerschueren/expiry-set), I'm looking in extracting the logic in a separate package. Still have some cleanup work to do and then actually extracting and releasing it as a package. But I believe it can easily be used by `mem`.

**Comment by SamVerschueren** [comment]
I implemented this in #19. Feel free to help testing and reviewing it.
